name = "Heine"
uuid = "28ce595a-678f-4b2c-aab1-76c8e0474aad"
authors = ["Heine Rugland"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
